String sourceFile = readFileFromWorkspace("${env.workspace}/utilities/MyUtilities.groovy")
println(sourceFile)
Class MyUtilities = new GroovyClassLoader(getClass().getClassLoader()).parseClass(sourceFile)
println(MyUtilities)
def myJob = job('Test/example')
MyUtilities.addMyFeature(myJob)