String sourceFile = readFileFromWorkspace("src/main/groovy/utilities/MyUtilities.groovy")
println(sourceFile)
Class MyUtilities = new GroovyClassLoader(getClass().getClassLoader()).parseClass(sourceFile)
println(MyUtilities)
MyUtilities obj1 = new MyUtilities()
def myJob = job('Test/example')
MyUtilities.addMyFeature(myJob)